---
title: "2022 Monthly Reports"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 2
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

Last compiled: `r Sys.Date()`

# **December 2022**
## Website
* Updated hours for finals on the Google Knowledge Panel
* Meeting with Ian on LibGuides stats on GA

## Workshops / Training 
* AI4LAM - 4 sessions


## Research
* Prepare for the podcast - new account on Buzzsprout; artwork, intro & extro music
* Proposed to D4D 2023


## Service
* CALA Membership Committee: maintain membership database, monthly meeting, work on joint project with PR & Fundraising Committee
* CALA PR & Fundraising Committee: 
    * Update page for donation and calendar page
    * Interview four CALA previous president and transcribe the talks
    * Review and revise calendar flyer

* IFLA SE: monthly meeting, update project page and satellite conference pages, respond to the question by email
* TTU CFSA: Maintain & share distribution list


## Others
* OA data compile and report
* download recital videos from Bilibili
* HEB volunteer
* Triaged and responded queries through website email
* attended interview of Assessment Librarian



# **November 2022**
## Website
* Continue updating personal librarians page
* Updated the print version of library map (ground floor)
* Add slideshow and event pages for bcc library homepage
* Remove Friends of Libraries
* Updated donation page, event space pages, Privacy policy, 
* Write instruction for HR on how to manage the staff directory

## Teaching
* Prepare for R workshop
* Consultancy on R
* Prepare for workshop - using R for text mining

## Workshops / Training 
* Webinar on e-resources
* AI4LAM - opening session

## Research
* Prepare for the podcast - look for possible host and platform
* Proposed to ARL Book chapter - Data Culture in Academic Libraries
* Started to work on paper about data literacy courses in MLIS


## Service
* CALA Membership Committee: maintain membership database, monthly meeting, process application for Dr. Li's scholarship, prepare member lists for CALA treasurer & Newsletter Committee
* UX/Website team meeting, SharePoint site migration
* CALA PR & Fundraising Committee: prepare CALA president interview; interview 2 former CALA presidents and transcribe the talks; work on 2023 calendar for donation purposes; serve as guest editor for the special issue of IJoL
* IFLA SE: monthly meeting, update project page
* TTU CFSA: Update website and distribution list
* Assessment Team: weekly meeting; website data for the Reach project; prepare and analyze LibGuide usage data (on Google Analysis)


## Others
* OA data compile and report
* Triaged and responded queries through website email
* attended interview of Digital Curation Librarian
* download recital videos from Bilibili


# **October 2022**
## Website
* Updated personal librarians page
* minor update: fix broken links, Stacks change on S4 and S5.
* started to update the print version of library map (ground floor)

## Teaching
* Tableau workshop
* Consultancy on R

## Workshops / Training 
* Tutorial video on Notion, a notetaking tool
* Webinar on Ex Libris Discovery

## Research
* Attended Access Conf - presented on using OpenRefine to extract information
* Attended SEDLS - presented in the poster session on data skills taught on campus
* prepare invited presentation for CALA webinar: If IFLA Right for You

## Service
* CALA Membership Committee: maintain membership database, summarize report on Dr. Lee's scholarship
* UX/Website team meeting
* CALA PR & Fundraising Committee: letter to potential sponsors, submit IRB request for the CALA president interviews,submitted invitation emails to CALA presidents 
* IFLA SE: plan the questionnaire project
* TTU CFSA: meeting on upcoming event, started to prepare Chinese New Year event
* Assessment Team: read report


## Others
* OA data compile and report
* Triaged and responded queries through website email
* attended interview of Digital Curation Librarian



# **September 2022**
## Website
* homepage update
* Pull hours for library services from LibCal and displayed on the web pages
* minor updates on SWC test page
* Updated pages for Access dept. 
* worked on video tutorials page
* page updates per request: OER, personal librarians, lean library

## Teaching
* R workshops (5 sessions)
* R consultancy
* work on simplify the R workshops

## Workshops / Training / Meeting
* FRC coffee break on SR faculty report
* Meeting the provost

## Research
* finalized the application documents for sabbatical application
* Analyzed syllabus for the poster session of SEDLS

## Service
* IFLA SE section monthly meeting, website updates, 
* Add TTU CFSA new members to website and distribution list
* CALA PR & Fundraising committee: prepare documents for CALA president interivews, call for papers (special issue, IJoL), attended CALASYS training
* CALA Membership Committee: monthly meeting, maintain membership database

## Others
* OA data compile and report
* Triaged and responded queries through website email


# **August 2022**
## Website
* Privacy policy update
* Minor updates on homepage - logo of ETD
* web page updates per request - HR pages, OA award pages and access updates, Evaluation page, basement map, Lean Library page
* worked on video tutorials page
* worked on the test page for SWC
* search box for the arch lib
* add new posts, responded to review, and add three Q&A on the library knowledge panel on GMB
* Updated the search box background on the library homepage, arch library (test page), and BCC site (test page)


## Teaching
* updated the guides for the R workshops
* prepared R workshops

## Workshops / Training / Meeting
* Excel workshops
* Faculty meeting
* Team chair meeting

## Research
* worked on the chapter for the Everyday Evidence Book
* prepared for Access Conference
* clean ref files on SWC website using OpenRefine
* Worked on grant for podcast
* read articles/report on website stats and faculty survey

## Service
* CALA Membership Committee: database maintenance, attended monthly meeting
* CALA PR & Fundraising committee projects - proposal for the CALA collections grant
* IFLA SE section: wrote news report, attended monthly meeting, call for new members, preparation for the satellite conf with Utrecht University in 2023


## Others
* OA data compile and report
* Triaged and responded queries through website email
* reports on IFLA WLIC for grants

# **July 2022**
## Website
* troubleshot accordion page for access dept. 
* Updated LibGuide profile
* Update pages per requests - jobs page, directory, org charts, 

## Teaching
* submitted workshop proposals for the Fall

## Workshops / Training
* Workshops on Excel
* Workshop on build a good dataset

## Research
* read R for text mining
* worked on SEDLS proposal
* attended LiLI conference and presented
* worked on sabbatical proposal
* attended IFLA WLIC - poster sessions, SE section meeting, sessions, and other sessions

## Service
* CALA Membership database maintenance
* TTU CFSA farewell card
* CALA PR & Fundraising Committee - projects to celebrate CALA's 50th anniversary
* ERL search - finalize documents

## Others
* OA data compile and report
* Triaged and responded queries through website email

# **June 2022**
## Website
* Webpage updates - event page, icon for hours, fix broken links, event space, personal librarians, org chart, directory, access group, SWC pages, BCC homepage
* Updated Video Tutorials page
* Updated guides on LibGuides for accessibility
* worked on Google Analytics data
* Updated LibGuide CSS file

## Teaching
* Prepared and conducted workshop on Excel for Prairie View A&M

## Workshops / Training / Conferences
* 4-half-day workshop by Carpentries
* Watched Digital Humanities workshop on YouTube

## Research
* prepared and conducted presentation on the LiLI Conference
* worked on grant for podcast
* Proposal to Southeast Data Librarian Symposium on *Data Skills Taught on Campus*
* read R for text mining
* prepared poster for IFLA Congress

## Service
* ERL search
* CALA Membership maintenance
* IFLA SE section monthly meeting
* UX/Website Team meeting
* TTU CFSA - prepare e-card for a retiree

## Others
* OA data compile and report
* Triaged and responded queries through website email


# **May 2022**

## Website
* Continued working on the [tutorial video page](https://www.depts.ttu.edu/library/test/tutorials2.php) & attended meetings
* Update library hours on Google knowledge panel and responded to reviews
* Updated pages - jobs, directory, org charts, and other pages
* Supported the creation of audio library tours


## Teaching
* Met faculty from [College of Nursing, PVAMU](https://www.pvamu.edu/nursing/) and continued preparing for the Excel workshop 


## Workshops / Training / Conferences
* Watched training videos about Excel dashboard
* AARC workshop: More Journal Articles and Fewer Books: Changing Publishing Practices in the Social Sciences
* Read books on Using R for text mining and Using R for data analysis in Social Sciences

## Research
* Applied for the International Travel Fund for [IFLA WLIC](https://2022.ifla.org/) 
* Started a grant idea for podcast


## Service
* CALA Election Committee - Prepare data for membership database maintenance
* ERL search - Phone interviews, Reference Checks, and certified the search
* IFLA monthly meeting and updated web pages for the SE site
* UX Team meeting
* Co-host workshop - HerStory: the legal history of Chinese American Women & edit transcript for the closed captioning
* Volunteer - Fuel for finals
* Review a proposal for the [Access Conference 2022](https://accessconference.ca/)


## Others
* Collected OA data for May and updated the OA data report
* Unit meetings
* Triaged and responded queries through website email



# **April 2022**

## Website
* Continued working on the [tutorial video page](https://www.depts.ttu.edu/library/test/tutorials2.php) and 2 other versions
* Updated pages - stacks, jobs, directory, and org charts
* Together with Melissa, updated the Wi-Fi page to fit mobile devices better
* Excluded docdel SAs from the GA stats
* Changed the search box on the BCC library's page >> search only the BCC collections now
* Worked on the KB article on creating a PRIMO search box
* Retrieved and reviewed website usage stats
* Updated lib hours, added new posts on Google Knowledge Panel, and responded reviews
* Updated building services distribution list

## Teaching
* Preparing for the Excel workshop for the [College of Nursing, PVAMU](https://www.pvamu.edu/nursing/)

## Workshops / Training
* Watched training videos about Excel dashboard
* Attended [Research Data Management Library Academy](https://rdmla.github.io/) Symposium


## Research
* Worked on and submitted proposal on pre- and post- pandemic library instructions for [IFLA WLIC](https://2022.ifla.org/) 
* Submitted a proposal on Using OpenRefine to Retrieve data from APIs to the [Access Conference 2022](https://accessconference.ca/)


## Service
* CALA membership database maintenance
* ERL search - Updated matrix and prepared phone interview questions
* UX Team meeting


## Others
* IFLA registration, visa application, and other paper work
* Prepared for the Carpentries Lesson Development Training
* Explored Scopus API and retrieved OA data through both Scopus API and Scopus application
* Prepared the exhibit of Herstory - meeting the speaker and set up the exhibit
* Unit meeting
* Co-chair meeting
* triaged queries through website email


# **March 2022**


## Website
* Updated jobs, directory, and org charts pages
* Updated Emergency Action Plan for the building services
* Worked on the [tutorial video page](https://www.depts.ttu.edu/library/test/tutorials2.php) - meeting RIO and UX, drafted test page
* Fixed broken links
* Meeting with Melissa about current projects ([BCC](https://www.depts.ttu.edu/library/bcclibrary/), [video tutorial page](https://www.depts.ttu.edu/library/test/tutorials2.php)) and daily maintenance
* Updated donation page


## Workshops / Training
* Watched training videos about Excel dashboard


## Research
* Worked on and submitted poster proposal for [IFLA WLIC](https://2022.ifla.org/) (accepted)
* Continued reading syllabus of data-related courses
* Worked on and submitted presentation proposal for the [LILi conference](https://lili.libguides.com/lili)


## Service
* IFLA Statistics & Evaluation Section monthly meeting - website and WLIC
* CALA membership database maintenance
* CALA Election committee - prepared list of eligeble members for the Election
* Faculty Search Committee (standing) meetings
* Reviewed a book chapter for the Everyday Evidence Book
* ERL search - first committee meeting, prepared documents for the search

## Others
* Monthly report (Feb, 2022) - took days to work on pivot table using R.
* Preparation for attending the IFLA WLIC
* Discussion on Herstory exhibit
* Applied for the CALA IFLA registration grant
* Took a 6-day vacation
* Unit meeting
* Annual review archive with HR


# **February 2022**

## Website
* Worked on the draft version of the [Black Culture Center Library website](https://www.depts.ttu.edu/library/bcclibrary/)
* Website updates - fixed some broken links, updated job posts, org charts, directory, donation links, 
* Request access for people from access and arch lib
* Responded to the suggestions on the [Software List](https://apps.lib.ttu.edu/services/technology/softOU.php), consulting the Library IT and the Technology Team
* Confirmed the renewal of ESI Application Registrations


## Meetings / Workshops
* Library Faculty Special Meeting
* Attended Making an Impact with Data Visualization - by UNC Libraries Research Hub
* UX Team meeting - sharing the updates of the [Software List](https://apps.lib.ttu.edu/services/technology/softOU.php) page
* Discussion on [Black Culture Center Library website](https://www.depts.ttu.edu/library/bcclibrary/)
* Attended Spreadsheets and OpenRefine [Data & Donuts Workshop] by UT Austin Libraries
* UK Carpentry Community Monthly Meeting - for information about the Carpentries Collaborative Lesson Development Training - proposed a project to the program after the meeting. The training probably starts in this June and followed with a 2-month course development and an evaluation/wrap-up. 
* Information session of the project - On the Books organized by the UNC Libraries

## Research
* Worked on the draft version of the book chapter for Data driven OA Initiative
* Preparing poster proposal for the IFLA WLIC 2022
* Data-related courses on 2021-2022 course catalog - information collection and analysis

## Service
* CFSA Event (New Year Celebration) and meeting
* Faculty Search Committee - Search for the Research Services Librarian: three onsite interviews
* Reviewed Code4Lib 2022 Conf. schedule
* CALA membership database maintenance - membership renewal for a group, membership scholarship updates
* Started to review a chapter for the book Everyday Evidence Book.
* IFLA SE Monthly Meeting: SE website, upcoming WLIC in July


## Others
* R workshop preparation, rehearsal, and delivery
* Help the Tableau workshop
* Triaged and responded emails to the website - 15 queries (the same as Jan)
* Read books and watch videos on R and R training




# **January 2022**

## Website

* [Black Culture Center Library website](https://www.depts.ttu.edu/library/bcclibrary/) started off
* Requested UX tests for the pages [Personal Librarians](https://www.depts.ttu.edu/library/research-support/personalLibrarians/) and [Software List](https://apps.lib.ttu.edu/services/technology/softOU.php) - reviewed and discussed the test plan
* Maintained [job posts](https://www.depts.ttu.edu/library/about/employment/), [staff directory](https://www.depts.ttu.edu/library/about/staff/index.php), and [org charts](https://www.depts.ttu.edu/library/about/admin/org_chart/org_charts.php)
* Updated the [Open Access Award Recipients](https://www.depts.ttu.edu/library/grants/open-access-award/recipients.php) page
* Helped styling of the chat widget on the [OneSearch](https://ttu-primo.hosted.exlibrisgroup.com/primo-explore/search?institution=01TTU&vid=01TTU&tab=default_tab&search_scope=01TTU_ALL&mode=Basic&displayMode=full&bulkSize=38&highlight=true&dum=true&query=any,contains,&displayField=all) page
* Updated links to the [Development Leave forms](https://www.depts.ttu.edu/library/libstaff/)
* Updated [Arch Library floor plans](https://www.depts.ttu.edu/library/about/facility/maps/arch.php)
* Fixed some broken links
* Confirm the renewal of ESI Application Registrations
* Responded to the UX report on the Personal Librarian's page
* Maintained Google Knowledge Panel, the right side box on Google Search results of "TTU Library" 

## Meetings / Workshops
* Software Carpentry II: Programming with Python by Virginia Tech Libraries
* Software Carpentry II: Programming with R and RStudio by Virginia Tech Libraries
* Library Faculty Meeting
* TX-CARP Monthly Meeting - information collection, 4 possible carpentry workshops
* Unit Meeting


## Research
* Reviewed the data for the book chapter on OA publishing
* Final revision of the paper "Applications, Issues and Reflection on Altmetrics" per editor's request

## Service
* FSC regular meetings, reference check, and phone interviews
* Code4Lib Conf Program Committee meetings - review and schedule programs
* CFSA Events (New Year Celebration) preparation and [website](https://www.depts.ttu.edu/cfsa/) updates 
* IFLA SE section monthly meeting - [section website](https://www.ifla.org/units/statistics-and-evaluation/) updates and programs for the upcoming WLIC 2022
* CALA membership database maintenance

## Others
* R workshops preparation, rehearsals, and deliveries (updated [LibGuides](https://guides.library.ttu.edu/R4Beginners))
* Annual Review
* Triaged and responded emails to the website - 15 queries
* Office rekeyed








