---
title: "Stats"
output: html_document
---

# OA Stats

1. Collected bibliographic records of articles, conf papers, reviews, books and book chapters which were affiliated with Texas Tech University and published in the years 2016 through 2020 on March 1st, 2022 and retrieved 10,498 records. 

The search query was 

> AF-ID(“Texas Tech University” 60021285) OR AF-ID(“Rawls College of Business” 60123664) AND ( LIMIT-TO ( PUBYEAR,2020) OR LIMIT-TO ( PUBYEAR,2019) OR LIMIT-TO ( PUBYEAR,2018) OR LIMIT-TO ( PUBYEAR,2017) OR LIMIT-TO ( PUBYEAR,2016) ) AND ( LIMIT-TO ( DOCTYPE,”ar” ) OR LIMIT-TO ( DOCTYPE,”cp” ) OR LIMIT-TO ( DOCTYPE,”re” ) OR LIMIT-TO ( DOCTYPE,”ch” ) OR LIMIT-TO ( DOCTYPE,”bk” ) )

2. Removed records with duplicated DOIs or without DOIs and cleared some author IDs. Only 9,819 records kept. 

3. Populated OA information through the Unpaywall API on March 1st and 2nd. 


The following table shows the count and percentage by OA status and year.


```{r, echo=FALSE}
# install.packages("qwraps2") # not used
# install.packages("gt") # not used
# install.packages("pivottabler")

library(tidyverse)
library(pivottabler)

oa_stats_march <- read_csv("data/oa_stats_20220301_clean.csv")

# qhpvt(oa_stats_march, c("is_oa","oa_status"), "Year", "n()") this code works for count, but not for percentage

oa4pivot <- oa_stats_march %>% 
  group_by(Year) %>% 
  count(is_oa, oa_status) %>%  
  mutate(percent = 100*n/sum(n)) %>%   # calculate the percentage
  ungroup() 

oa4pivot$is_oa <- as.character(oa4pivot$is_oa)  #convert is_oa from logic to character

oa4pivot %>%   
  qhpvt(
    c("is_oa","oa_status"), 
    "Year", 
    c("Count" = "sum(n)", "%" = "sum(percent)"),
    formats = list("%.0f", "%.2f"),
    totals = list("is_oa" = "Total", "oa_status" = "Total"),
    totalStyle = list("font-weight"="bold")
    )

# not sure how to remove the Total column for Year
# pt <- PivotTable$new()
# pt$addData(oa4pivot)
# pt$addColumnDataGroups("Year")
# pt$addRowDataGroups("is_oa", 
#                     outlineTotal=list(groupStyleDeclarations=list(color="black")))
# pt$addRowDataGroups("oa_status",
#                     outlineTotal=list(groupStyleDeclarations=list(color="black")))
# pt$defineCalculation(calculationName = "count", summariseExpression = "sum(n)")
# pt$defineCalculation(calculationName = "%", summariseExpression = "round(sum(percent))")
# pt$renderPivot()

```
Comparing the OA status information from Scopus and Unpaywall:
* The OA count were almost the same;
* The count of each specific OA status were different, need to choose one source to track the trends. I suggested we use Scopus data only.
* The **overall journal article OA percentage was 45%** and **conference proceedings was around 10%**. 
* Another finding - Scopus updates its data constantly. The data retrieved on March 1st and March 3rd using the same query were a little bit different. Next month, I will try to use the Scopus API to track the OA status and citations for the data set of 10,498 records (retrieved on March 1st, 2022). 

# Web Stats
